### ISSUE TITLE
'asdf' project comparisons and differences

### ISSUE THREAD

**Issue by dimakis** [aerogear/charmil#23]
Hey all.

I was looking into the aerogear/charmil project over the last couple of days to get a sense of what's going on. It reminds me a lot of the 'asdf' project. Do any of ye know of it? 

--github
https://github.com/asdf-vm/asdf

-- list of all plugins currently available
https://asdf-vm.com/#/plugins-all

Is it vastly different? I know it'll be written in GoLang as opposed to shell but I'm wondering about the desired functionality for it the differences and/ or similarities. 
Just thought I'd open a bit of a discussion about it.

**Comment by wtrocki** [comment]
This is another great project to look at for inspiration. 
My take is that this project deals with distribution and versioning, but since it is written in bash we cannot reuse it much (as we are doing golang). My take is to have diversity and study as much of version managers that offer kind of plugin support.

However our take would be to deliver something more framework/low level integration specific so we will be able to give impression that you dealing wit the same tool etc.

**Comment by ankithans** [comment]
commands are quite similar to [krew](https://github.com/kubernetes-sigs/krew/)   some more cmds are there in [asdf cmds](https://github.com/asdf-vm/asdf/blob/master/help.txt)
They have diff structure for [plugin-index](https://github.com/asdf-vm/asdf-plugins) (only consists of plugin's repo URL).

I found one more
[Jfrog](https://www.jfrog.com/confluence/display/CLI/JFrog+CLI#JFrogCLI-InstallingPlugins) https://github.com/jfrog/jfrog-cli-plugins-reg

**Comment by wtrocki** [comment]
> They have diff structure for plugin-index (only consists of plugin's repo URL).

yes this is way to simple, comparing to krew which is advanced. For POC we probably want to stay somewhere between - allow versioning in schema, but do not implement advanced handling etc.

**Comment by wtrocki** [comment]
Great to have this link. We diverged from this now towards having embedded library. Closing
